#! /bin/bash
# mntssh - Use sshfs to mount disk on ~/mnt
# Usage: mntssh [-r] username@server
#

if [[ "$1" == "" ]]; then
	echo "usage: mntssh [-r] user@server"
	exit -1

elif [[ "$1" == "-r" ]]; then
  user=`echo $2 | sed "s/@.*//g"`
  server=`echo $2 | sed "s/${user}@//g"`
  mkdir -p $HOME/mnt/$server
  [ "$(ls -A $HOME/mnt/$server)" ] && echo "mntssh: Mount point in use" && exit -1
  sshfs $2:/ $HOME/mnt/$server

else
  user=`echo $1 | sed "s/@.*//g"`
  server=`echo $1 | sed "s/${user}@//g"`
  mkdir -p $HOME/mnt/$1
  [ "$(ls -A $HOME/mnt/$1)" ] && echo "mntssh: Mount point in use" && exit -1
  sshfs $1:/home/$user $HOME/mnt/$1

fi

