#!/bin/bash

#
# Plugins
#

chunkc core::plugin_dir ~/.chunkwm_plugins

chunkc core::load tiling.so
# chunkc core::load border.so
# chunkc core::load ffm.so

#
# Configs
#

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set global_desktop_mode           float
chunkc set 1_desktop_mode                monocle

chunkc set global_desktop_offset_top     20
chunkc set global_desktop_offset_bottom  20
chunkc set global_desktop_offset_left    20
chunkc set global_desktop_offset_right   20
chunkc set global_desktop_offset_gap     15

chunkc set 1_desktop_offset_top          0
chunkc set 1_desktop_offset_bottom       0
chunkc set 1_desktop_offset_left         0
chunkc set 1_desktop_offset_right        0
chunkc set 1_desktop_offset_gap          0

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#

chunkc set mouse_modifier                fn

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       0

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

#
# NOTE: the following are config variables for the chunkwm-border plugin.
#

chunkc set focused_border_color          0xdd202020
chunkc set focused_border_width          5
chunkc set focused_border_radius         5
chunkc set focused_border_skip_floating  1

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#

#
# Declare floating windows.
#

chunkc tiling::rule --owner \"App Store\" --state float
chunkc tiling::rule --owner 1Password --state float
chunkc tiling::rule --owner \"1Password 6\" --state float
chunkc tiling::rule --owner \"備忘錄\" --state float
chunkc tiling::rule --owner \"便條紙\" --state float
chunkc tiling::rule --owner \"地圖\" --state float
chunkc tiling::rule --owner \"提醒事項\" --state float
chunkc tiling::rule --owner \"聯絡資訊\" --state float
chunkc tiling::rule --owner \"計算機\" --state float
chunkc tiling::rule --owner \"系統偏好設定\" --state float
chunkc tiling::rule --owner \"行事曆\" --state float
chunkc tiling::rule --owner \"訊息\" --state float
chunkc tiling::rule --owner \"照片\" --state float
chunkc tiling::rule --owner \"字體簿\" --state float
chunkc tiling::rule --owner \"辭典\" --state float
chunkc tiling::rule --owner \"文字編輯\" --state float
chunkc tiling::rule --owner Franz --state float
chunkc tiling::rule --owner Station --state float
chunkc tiling::rule --owner OmniFocus --state float
chunkc tiling::rule --owner Calendar --state float
chunkc tiling::rule --owner Dash --state float
chunkc tiling::rule --owner DaisyDisk --state float
chunkc tiling::rule --owner Photos --state float
chunkc tiling::rule --owner iTunes --state float
chunkc tiling::rule --owner Contacts --state float
chunkc tiling::rule --owner LICEcap --state float
chunkc tiling::rule --owner Spotify --state float
chunkc tiling::rule --owner ImageOptim --state float
chunkc tiling::rule --owner ImageAlpha --state float
chunkc tiling::rule --owner Notes --state float
chunkc tiling::rule --owner FaceTime --state float
chunkc tiling::rule --owner Bear --state float
# chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner Spotify --role AXWindow --subrole AXDialog --state tile


chunkc set monitor_focus_cycle 0
chunkc set window_focus_cycle none
