#!/usr/bin/env bash
# Launches appium installed under the global Node.js.

set -euo pipefail

SCRIPT_PATH="${BASH_SOURCE[0]:-$0}"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"

source "${SCRIPT_DIR}/utils/find_global_command_path.sh"
appium_path=$(find_global_command_path "node" "appium" "npm i --location=global appium" "$SCRIPT_PATH")

exec "$appium_path" "$@"
