#!/usr/bin/env bash
# -------------------------------------------------------------------
# set-start
# -------------------------------------------------------------------

SUBJECT=edit-start
VERSION=0.0.1
USAGE="edit-start"
HELP="
$USAGE

    Edit \"start\" commands for the current directory.
"

# --- Option Processing ---------------------------------------------

# Transform long options to short ones
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    *)        set -- "$@" "$arg"
  esac
done

while getopts ":vhnd:" optname
  do
    case "$optname" in
      "v")
        echo "$SUBJECT version $VERSION"
        exit 0;
        ;;
      "h")
        echo "$HELP"
        project_dir="$(pwd)"
        project_dir_hash="$(echo "$project_dir" | openssl md5)"
        start_files_path="$HOME/.start"
        start_file_path="$start_files_path/$project_dir_hash"
        if [ -f "$start_file_path" ]; then
          echo "Available Types:"
          sed "s/^/  /g" < "$start_file_path"
        fi
        echo ''
        echo "Use the 'set-start' or 'edit-start' command to add or edit start commands."
        exit 0;
        ;;
      "?")
        echo "Unknown option: -$OPTARG" >&2
        echo "Usage: $USAGE"
        exit 1;
        ;;
      ":")
        echo "No argument value for option $OPTARG" >&2
        echo "Usage: $USAGE"
        exit 1;
        ;;
    esac
  done

shift $(($OPTIND - 1))


# --- Script Body ---------------------------------------------------

set -eu

project_dir="$(pwd)"
project_dir_hash="$(echo "$project_dir" | openssl md5)"
start_files_path="$HOME/.start"
start_file_path="$start_files_path/$project_dir_hash"

if [ ! -e "$start_file_path" ]; then
  echo "Creating start file: \"$start_file_path\""
  echo 'default: echo "hi"' > "$start_file_path"
fi

"$EDITOR" "$start_file_path"
