#!/bin/bash
# -------------------------------------------------------------------
# set-update
# -------------------------------------------------------------------

SUBJECT=set-update
VERSION=0.0.1
USAGE="set-update [type=default] <command>"
HELP="
$USAGE

    Set the \"update\" command for the current directory.
"

# --- Option Processing ---------------------------------------------

# Transform long options to short ones
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    *)        set -- "$@" "$arg"
  esac
done

while getopts ":vhnd:" optname
  do
    case "$optname" in
      "v")
        echo "$SUBJECT version $VERSION"
        exit 0;
        ;;
      "h")
        echo "$HELP"
        exit 0;
        ;;
      "?")
        echo "Unknown option: -$OPTARG" >&2
        echo "Usage: $USAGE"
        exit 1;
        ;;
      ":")
        echo "No argument value for option $OPTARG" >&2
        echo "Usage: $USAGE"
        exit 1;
        ;;
    esac
  done

shift $(($OPTIND - 1))

# --- Arguments and Default Values ----------------------------------

command=''
type='default'

# --- Arguments Processing ------------------------------------------

if [ -n "$2" ]; then
  type="$1"
  command="$2"
else
  command="$1"
fi

if [ -z "$command" ]; then
  echo "No command specified" >&2
  echo "Usage: $USAGE"
  exit 1;
fi

command="${command/\//\\/}"

# --- Script Body ---------------------------------------------------

set -eu

project_dir="$(pwd)"
project_dir_hash="$(echo "$project_dir" | openssl md5)"

update_files_path="$HOME/.update"

mkdir -p "$update_files_path"

update_file_path="$update_files_path/$project_dir_hash"

if [ ! -e "$update_file_path" ]; then
  echo "Creating update file: \"$update_file_path\""
  echo 'default: ' > "$update_file_path"
fi

sed "/^${type}: .*\$/{h;s/^${type}: .*$/${type}: ${command}/;}
\${x
/^\$/{s//${type}: ${command}/;H;}
x
}" "$update_file_path" > "${update_file_path}_tmp"
rm -r "$update_file_path"
mv "${update_file_path}_tmp" "$update_file_path"

echo "update file $update_file_path updated:"
echo ''
cat "$update_file_path"
echo ''
echo "You can use the command 'update [type=default]' to boot up the project"
